name: Deploy to Dagster Cloud Serverless
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  dagster-cloud-deploy:
    runs-on: ubuntu-latest
    name: Deploy to Dagster Cloud
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dagster Cloud CLI
      run: |
        pip install dagster-cloud[docker]
        
    - name: Remove conflicting config and create workspace.yaml
      run: |
        # Remove existing dagster_cloud.yaml if it exists
        rm -f dagster_cloud.yaml
        
        # Create fresh workspace.yaml
        cat > workspace.yaml << EOF
        locations:
          - location_name: dagster-cloud
            image: ghcr.io/csw191/dagster-cloud:latest
            code_source:
              package_name: dagster_cloud
        EOF
        
        echo "Created workspace.yaml:"
        cat workspace.yaml
        
    - name: Deploy to Dagster Cloud
      env:
        DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
      run: |
        # Replace with your actual organization and deployment names
        ORGANIZATION_NAME="mt-hhs"
        DEPLOYMENT_NAME="prod"  # Change this to your actual deployment name
        
        echo "Using organization: $ORGANIZATION_NAME"
        echo "Using deployment: $DEPLOYMENT_NAME"
        echo "API Token length: ${#DAGSTER_CLOUD_API_TOKEN}"
        
        # Check which config files exist
        echo "Available config files:"
        ls -la *.yaml *.yml 2>/dev/null || echo "No YAML files found"
        
        # Use explicit workspace file parameter with dagster_cloud.yaml
        dagster-cloud workspace sync --organization "$ORGANIZATION_NAME" --deployment "$DEPLOYMENT_NAME" --workspace dagster_cloud.yaml
